services:
  - type: web
    name: javafx-spacewar
    env: ubuntu
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y openjdk-17-jdk maven
      mvn clean install
    startCommand: mvn jpro:run

